export const ORIGINAL_HEIGHT = 960
export const ORIGINAL_WIDTH = 1920

export const NAV_HEIGHT = 88
export const CANVAS_MIN_WIDTH = 1200
export const CANVAS_HEIGHT = ORIGINAL_HEIGHT - NAV_HEIGHT

export const PROJECT_WIDTH = 1200
export const PROJECT_HEIGHT = CANVAS_HEIGHT - NAV_HEIGHT
export const PROJECT_GAP = 360
export const PROJECT_TITLE_WIDTH = 512

export const PROJECT_CARD_LONGER_SIDE = 200
export const PROJECT_CARD_SHORTER_SIDE = 125

export const PROJECT_CARD_HOVER_WIDTH = 400
export const PROJECT_CARD_HOVER_HEIGHT = 250

export const PROJECT_COVER_WIDTH = 1200
export const PROJECT_COVER_HEIGHT = 960